slug: lf-decentralized-trust
landscapeMemberClasses:
  - name: Premier Membership
    category: Premier
  - name: General Membership
    category: General
  - name: Associate Membership
    category: Associate
landscapeMemberCategory: LF Decentralized Trust Members
memberSuffix: ' (member)'
