---
landscapeName: hl
landscapeMemberClasses:
  - name: Premier Membership
    category: Premier
  - name: General Membership
    category: General
  - name: Associate Membership
    category: Associate
project: a0941000002wByYAAU  # Hyperledger 
landscapeMemberCategory: Hyperledger Members
landscapefile: landscape.yml
missingcsvfile: missing.csv
